version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - fastapi
